--- 
abstract: Devel::StackTrace + PadWalker
author: 
  - Shawn M Moore, C<< <sartak@gmail.com> >>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.70
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Devel-StackTrace-WithLexicals
no_index: 
  directory: 
    - inc
    - t
requires: 
  Devel::StackTrace: 1.1902
  PadWalker: 0
version: 0.02
