---
abstract: 'Devel::StackTrace + PadWalker'
author:
  - 'Shawn M Moore, C<sartak@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-StackTrace-WithLexicals
no_index:
  directory:
    - inc
    - t
requires:
  Devel::StackTrace: 1.25
  PadWalker: 1.92
  perl: 5.8.1
resources:
  homepage: http://github.com/sartak/Devel-StackTrace-WithLexicals/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/sartak/Devel-StackTrace-WithLexicals.git
version: 0.08
